const LOCALITATI_OLT = [
  'Slatina',
  'Caracal',
  'Balș',
  'Corabia',
  'Scornicești',
  'Drăgănești-Olt',
  'Piatra-Olt',
  'Potcoava',
  'Osica-de-Sus',
  'Izbiceni',
  'Fărcaşele',
  'Curtișoara',
  'Brastavățu',
  'Rusănești',
  'Tia Mare',
  'Iancu Jianu',
  'Mărunței',
  'Găneasa',
  'Fălcoiu',
  'Valea Mare',
  'Ianca',
  'Dobrosloveni',
  'Crâmpoia',
  'Dăneasa',
  'Izvoarele',
  'Movileni',
  'Pleșoiu',
  'Strejești',
  'Bobicești',
  'Radomirești',
  'Vădăstrița',
  'Cilieni',
  'Traian',
  'Deveselu',
  'Vișina',
  'Scărișoara',
  'Șerbănești',
  'Văleni',
  'Gostavățu',
  'Brebeni',
  'Pârșcoveni',
  'Grojdibodu',
  'Tufeni',
  'Schitu',
  'Coteana',
  'Verguleasa',
  'Brâncoveni',
  'Redea',
  'Vâlcele',
  'Slătioara',
  'Rotunda',
  'Obârșia',
  'Bârza',
  'Cârlogani',
  'Grădinari',
  'Morunglav',
  'Teslui',
  'Stoicănești',
  'Gârcov',
  'Studina',
  'Orlea',
  'Corbu',
  'Sprâncenata',
  'Vulpeni',
  'Vulturești',
  'Stoenești',
  'Giuvărăști',
  'Vitomirești',
  'Cungrea',
  'Găvănești',
  'Poboru',
  'Sârbii - Măgura',
  'Urzica',
  'Băbiciu',
  'Colonești',
  'Bucinișu',
  'Bălteni',
  'Vlădila',
  'Voineasa',
  'Vișina Nouă',
  'Drăghiceni',
  'Seaca',
  'Spineni',
  'Perieți',
  'Ștefan Cel Mare',
  'Călui',
  'Dobroteasa',
  'Cezieni',
  'Ghimpețeni',
  'Gura Padinii',
  'Icoana',
  'Grădinile',
  'Milcov',
  'Priseaca',
  'Mihăești',
  'Osica-de-Jos',
  'Bărăști',
  'Șopârlița',
  'Ipotești',
  'Vădastra',
  'Leleasca',
  'Oboga',
  'Dobrun',
  'Oporelu',
  'Făgețelu',
  'Dobretu',
  'Sâmburești',
  'Nicolae Titulescu',
  'Optași-Măgura',
  'Tătulești',
  'Topana',
  'Baldovinești',
];

export default LOCALITATI_OLT;
